themeName: rafhun
devUrl: http://wpbp.dev
dbDump: db/
rootFolder: wwwroot/

buildFolders:
  documentation: documentation/
  fonts: fonts/
  icons: icons/
  images: images/
  js: js/
  languages: languages/
  styleguide: styleguide/
  theme: wp-content/themes/

srcFolders:
  bower: src/bower_components/
  config: src/config/
  css: src/css/
  fonts: src/fonts/
  icons: src/icons/
  iconsMin: src/icons/min/
  images: src/images/
  imagesUpload: src/uploads/
  imagesToUpload: src/uploads/dist/
  js: src/js/
  jsBuild: src/js/build/
  jsMolecules: src/js/molecules/
  languages: languages/
  php: src/php/
  scss: src/scss/
