themeName: themeNamePlaceholder
dockerName: dockerNamePlaceholder
devUrl: http://localhost:8080
dbDump: db/
rootFolder: wwwroot/

wordpress:
  locale: de_CH
  version: 4.8.1

buildFolders:
  fonts: fonts/
  icons: icons/
  images: images/
  js: js/
  languages: languages/
  plugins: wp-content/plugins/
  styleguide: styleguide/
  themes: wp-content/themes/

srcFolders:
  config: src/config/
  css: src/css/
  customPlugins: src/plugins/
  customThemes: src/themes/
  fonts: src/fonts/
  grunticon: src/.grunticon/
  icons: src/icons/
  iconsMin: src/icons/.min/
  images: src/images/
  imagesUpload: src/uploads/
  imagesToUpload: src/uploads/dist/
  js: src/js/
  jsMolecules: src/js/molecules/
  jsNoConcat: src/js/no-concat/
  languages: src/languages/
  php: src/php/
  scss: src/scss/
